### ISSUE TITLE
显示成功了，但是bot没反应

### ISSUE THREAD

**Issue by ytb1079014809** [xiaomaoJT/TgBot#1]
{"ok":true,"result":true,"description":"Webhook is already set"}

**Comment by xiaomaoJT** [comment]
{"ok":true,"result":true,"description":"Webhook is already set"}
此反馈只能说明机器人已成功开启会话链接。


请尝试勘查以下几点以排查故障：
1、查看对应google excel中是否有成功存储信息。2、尝试私信机器人是否反应。


以上无反应，请检查脚本是否有错误删减而报错，可查询执行记录







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月23日(星期五) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xiaomaoJT/TgBot] 显示成功了，但是bot没反应 (Issue #1)





 
{"ok":true,"result":true,"description":"Webhook is already set"}

**Comment by ytb1079014809** [comment]
> {"ok":true,"result":true,"description":"Webhook is already set"} 此反馈只能说明机器人已成功开启会话链接。 请尝试勘查以下几点以排查故障： 1、查看对应google excel中是否有成功存储信息。2、尝试私信机器人是否反应。 以上无反应，请检查脚本是否有错误删减而报错，可查询执行记录
> […](#)

感谢🥹大佬！

**Comment by leanovv** [comment]
function myFunction() { }初始的这个要删除吗
删除后运行调试 提示
TypeError: Cannot read properties of undefined (reading 'postData')
doPost	@ swarm_tg.gs:62

**Comment by xiaomaoJT** [comment]
初始内容全部删掉

**Comment by xiaomaoJT** [comment]
> function myFunction() { }初始的这个要删除吗
> 删除后运行调试 提示
> TypeError: Cannot read properties of undefined (reading 'postData')
> doPost @ swarm_tg.gs:62

初始函数全部清除

**Comment by leanovv** [comment]
![image](https://github.com/xiaomaoJT/TgBot/assets/30551116/85044c59-30f9-412a-8400-4e6f2a3bbc71)
会提示这个，表格里面也没有数据

**Comment by xiaomaoJT** [comment]
> ![image](https://user-images.githubusercontent.com/30551116/256716884-85044c59-30f9-412a-8400-4e6f2a3bbc71.png)
> 会提示这个，表格里面也没有数据

无法直接运行喔，需要通过tg机器人来执行，直接运行缺少关键数据，可查看项目内样例demo

**Comment by leanovv** [comment]
还是不行啊，按照教程配置表格和app脚本，连接也通了，机器人那边还做什么配置，输入了信息，表格里面没有数据。

**Comment by xiaomaoJT** [comment]
> 还是不行啊，按照教程配置表格和app脚本，连接也通了，机器人那边还做什么配置，输入了信息，表格里面没有数据。

建议你这边私聊机器人，上传部份你的代码以排查原因。https://t.me/Xiao_MaoMao_bot

**Comment by xiaomaoJT** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
