### ISSUE TITLE
群聊功能bug

### ISSUE THREAD

**Issue by bili-jing** [xiaomaoJT/TgBot#3]
<img width="620" alt="image" src="https://github.com/xiaomaoJT/TgBot/assets/45563478/50ba7d39-3fa5-4a23-9ec8-f9ae32e58607">
群聊的消息id，怎么拿去跟用户id判断呢，应该拿from.id呀

**Comment by xiaomaoJT** [comment]
怎么能是bug呢，目前设计的管理员功能仅限bot私有者方可操控，故在操作前对操作人进行了判断。要说是bug ，只能说当用户未关注bot时，操作后无法进行通讯而出现的错误，最新版本已修复。

**Comment by bili-jing** [comment]
问题是在群聊里面，拿到的是群id呀。你自己试试就知道了，我是所有者，并且也是管理员，发现不行。一看源码，你判断了群id，而不是发送者的id，应该取from，而不是chat的

**Comment by xiaomaoJT** [comment]
有道理，也许有差异数据，我这边测试通过私聊时候，chat- ID和 from - ID 是一致的

**Comment by xiaomaoJT** [comment]
大概懂你意思了，不过目前管理功能主要是通过bot进行隐形操作，所以才没有在群聊内开放。

**Comment by bili-jing** [comment]
可以说明隐形操作么，文档没有具体写清楚交互方式

**Comment by xiaomaoJT** [comment]
暂无详细文档，可通过XiaoMao频道，搜索 #TgBot仓库更新 标签查看部分能力更新图文说明。
已升级一个版本，可通过群聊释放管理能力，可更新查看。
