### ISSUE TITLE
类型错误：无法读取未定义的属性（读取“内容”）（第 233 行，文件“Code”）

### ISSUE THREAD

**Issue by Post123123** [xiaomaoJT/TgBot#5]
类型错误：无法读取未定义的属性（读取“内容”）（第 233 行，文件“Code”）
![image](https://github.com/xiaomaoJT/TgBot/assets/165189083/b2345308-ffbc-44e2-823c-461e49156c60)

**Comment by xiaomaoJT** [comment]
信息太少无法辨别错误，请确保GAS与TGBOT已成功链接

**Comment by xiaomaoJT** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
