### ISSUE TITLE
请问这是什么情况, 到激活的那一步链接不上.

### ISSUE THREAD

**Issue by sirblangch** [xiaomaoJT/TgBot#7]
![image](https://github.com/xiaomaoJT/TgBot/assets/167659962/1f7eb4cb-49ea-4116-8ba8-67659ebcd021)

就是直接复制应用地址, 提示: 找不到 doPost函数

**Comment by sirblangch** [comment]
![image](https://github.com/xiaomaoJT/TgBot/assets/167659962/b2be94fb-18c1-465b-9eb3-995d0173084f)

**Comment by sirblangch** [comment]
![image](https://github.com/xiaomaoJT/TgBot/assets/167659962/0bbb2a3c-88d2-4531-983f-e8e96614eb53)

**Comment by sirblangch** [comment]
![image](https://github.com/xiaomaoJT/TgBot/assets/167659962/30bc9e55-c9ce-47be-a34c-3102c5e44efe)

我有保存的, 入口函数是这个嘛, 没错啊

**Comment by xiaomaoJT** [comment]
https://api.telegram.org/bot 你的tg机器人Token /setWebhook?url=你的web应用网址
//上面链接替换 你的tg机器人Token和你的web应用网址 内容即可
//注意链接不要留空格
//注意token前面有bot需要保留

**Comment by sirblangch** [comment]
![image](https://github.com/xiaomaoJT/TgBot/assets/167659962/d6f07b19-39e4-4aab-8100-22dc24eda4e9)

**Comment by xiaomaoJT** [comment]
表格id错了，/后面的都不要

**Comment by sirblangch** [comment]
我知道啊, 就是不要后面是这个错误, 我才又加上的.. 
说明这不是关键错误, 
去掉还是同样的错误

**Comment by xiaomaoJT** [comment]
https://api.telegram.org/bot 你的tg机器人Token /setWebhook?url=你的web应用网址
//上面链接替换 你的tg机器人Token和你的web应用网址 内容即可
//注意链接不要留空格
//注意token前面有bot需要保留

检查这一块吧，比如空格问题

**Comment by sirblangch** [comment]
好了好了!

**Comment by sirblangch** [comment]
大佬请问有指令文档吗,我没找到.
然后采集群消息, 我想只采集被艾特的消息, 而不是无差别采集. 
或者把群采集关闭, 用啥指令噢

**Comment by xiaomaoJT** [comment]
更多配置参见仓库首页快速导航目录了解
