### ISSUE TITLE
关键字自动回复问题

### ISSUE THREAD

**Issue by kufei326** [xiaomaoJT/TgBot#9]
我把表格里面的关键字全部删除后新建自己的关键字，然后机器人无论什么信息都会回复！

**Comment by xiaomaoJT** [comment]
贴图呀或上传excel

**Comment by kufei326** [comment]
![IMG_5106](https://github.com/user-attachments/assets/698d3b59-1fd6-4890-9d4d-be443983bff1)
![IMG_5105](https://github.com/user-attachments/assets/b534ddbd-3d03-43a4-a63e-03127ee686ac)

**Comment by xiaomaoJT** [comment]
建议将后面的空白行全选中并删除行

**Comment by kufei326** [comment]
感谢大佬帮助，没注意后面还有
